In [31]:
import os
import seaborn as sns
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import numpy as np

from hbn.constants import Defaults
from hbn.data import data_widgets

%load_ext autoreload
%autoreload 2

import warnings
warnings.filterwarnings('ignore')

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [38]:
# interactive data widget

phenotype_widget = data_widgets.get_phenotype_inputs()
display(phenotype_widget)

participant_widget = data_widgets.get_participant_inputs()
display(participant_widget)

VBox(children=(Dropdown(options=('Child Measures', 'Parent Measures', 'Teacher Measures'), value='Child Measur…

VBox(children=(Dropdown(options=('train', 'test', 'all'), value='train'), Dropdown(options=(), value=None), Se…

In [50]:
# get features and target
features, target = data_widgets.get_data(phenotype_widget, participant_widget, preprocess=False)

# create dataframe (merging features + target)
df = pd.concat([pd.DataFrame(target), features], axis=1)

reading /Users/maedbhking/Documents/healthy_brain_network/data/raw/phenotype/Parent_Measures/Interview_of_Emotional_and_Psychological_Function/Intake_Interview.csv into dataframe
reading /Users/maedbhking/Documents/healthy_brain_network/data/raw/phenotype/Clinical_Measures/Clinical_Diagnosis_Demographics.csv into dataframe

In [52]:
df

,DX_01,"PreInt_Demos_Fam,Administration","PreInt_Demos_Fam,Child_CountryOrigin","PreInt_Demos_Fam,Child_Ethnicity","PreInt_Demos_Fam,Child_Race","PreInt_Demos_Fam,Child_Race_Other","PreInt_Demos_Fam,DP_Yrs","PreInt_Demos_Fam,Data_entry","PreInt_Demos_Fam,Days_Baseline","PreInt_Demos_Fam,Divorced_Yrs",...,"PreInt_TxHx,pmed_09_type","PreInt_TxHx,pmed_10_dose","PreInt_TxHx,pmed_10_name","PreInt_TxHx,pmed_10_type","PreInt_TxHx,psych_meds_cur","PreInt_TxHx,psych_meds_past","PreInt_TxHx,serious_injury","PreInt_TxHx,suicide","PreInt_TxHx,trauma","PreInt_TxHx,﻿EID"
0,ADHD-Combined Type,All,USA,0.0,0.0,NaN,NaN,Complete,93.0,3.0,...,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0.0,0.0,NaN
1,ADHD-Inattentive Type,All,USA,2.0,9.0,Mixed,NaN,Complete,114.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN
2,ADHD-Inattentive Type,All,USA,0.0,NaN,NaN,NaN,Complete,117.0,NaN,...,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,NaN
3,ADHD-Combined Type,All,United States,0.0,0.0,NaN,NaN,Complete,0.0,NaN,...,NaN,NaN,NaN,NaN,0.0,1.0,0.0,1.0,1.0,NaN
4,ADHD-Inattentive Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1639,ADHD-Inattentive Type,All,USA,1.0,1.0,NaN,NaN,Complete,56.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN
1640,ADHD-Hyperactive/Impulsive Type,All,United States,0.0,0.0,NaN,NaN,Complete,41.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,NaN,NaN
1641,ADHD-Inattentive Type,All,United States,NaN,0.0,NaN,NaN,Complete,29.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,NaN
1642,ADHD-Inattentive Type,All,USA,0.0,0.0,NaN,NaN,Complete,44.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN
1643,Other Specified Attention-Deficit/Hyperactivit...,All,United States,1.0,0.0,NaN,NaN,Complete,29.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN

In [47]:

adhd = df[df["PreInt_FamHx,m_adhd"]==1].groupby('DX_01').agg({"PreInt_FamHx,m_adhd": 'count'})
total = df.groupby('DX_01').agg({"PreInt_FamHx,m_adhd": 'count'})

percent = adhd / total

Empty DataFrame
Columns: []
Index: []